name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test1
      id: test1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test1
        setup-command: pip install -r .tests/test_requirements.txt
        command: pytest .tests/test_modularity.py::test_1_modularity
        timeout: 10
        max-score: 30
    - name: Test2
      id: test2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test2
        setup-command: pip install -r .tests/test_requirements.txt
        command: pytest .tests/test_modularity.py::test_2_girvan_newman
        timeout: 10
        max-score: 30
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST1_RESULTS: "${{steps.test1.outputs.result}}"
        TEST2_RESULTS: "${{steps.test2.outputs.result}}"
      with:
        runners: test1,test2
